### ISSUE TITLE
Network should be a property of the xSlot instead of Partner level property

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/oath-adapter#3]
This will most likely affect the following areas:
* The config validator file
https://github.com/indexexchange/oath-adapter/blob/master-v2/oath-htb-validator.js#L54
* The adapter section which consumes the config and crafts the bid request
https://github.com/indexexchange/oath-adapter/blob/master-v2/oath-htb.js#L133
* The appropriate spec files need to be updated
https://github.com/indexexchange/oath-adapter/blob/master-v2/spec/support/mockPartnerConfig.json

Feel free to update any other files that may be relevant

**Comment by slimkrazy** [comment]
Hi folks, 

Can somebody grant me push permissions to this repo? Here's the error I receive when trying to push up a branch with the fixes:

remote: Permission to indexexchange/oath-adapter.git denied to slimkrazy.
fatal: unable to access 'https://github.com/indexexchange/oath-adapter.git/': The requested URL returned error: 403

**Comment by slimkrazy** [comment]
Resolved in PR #6
