### ISSUE TITLE
Region should be a property of the xSlot instead of Partner level property

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/oath-adapter#4]
This will most likely affect the following areas:
* The config validator file
https://github.com/indexexchange/oath-adapter/blob/master-v2/oath-htb-validator.js#L46
* The adapter section which consumes the config and crafts the bid request
https://github.com/indexexchange/oath-adapter/blob/master-v2/oath-htb.js#L133
* The appropriate spec files need to be updated
https://github.com/indexexchange/oath-adapter/blob/master-v2/spec/support/mockPartnerConfig.json

Feel free to update any other files that may be relevant

**Comment by slimkrazy** [comment]
Resolved in PR #6
